package com.isrbet.budgetsbyisrbet

import org.junit.Assert
import org.junit.Before
import org.junit.Test

class GetBudgetAmountTest {
    @Before
    fun prepareForTesting() {
        gCurrentDate = MyDate(2023, 4, 9)
    }
    @Test
    fun budgetAmountTest() {
        val spenderModel = SpenderViewModel()
//        spenderModel.clearCallback()
        val catModel = CategoryViewModel()
//        catModel.clearCallback()
        val budgetModel = BudgetViewModel()
//        budgetModel.clearCallback()
        val expModel = TransactionViewModel()
//        expModel.clearCallback()
        val defModel = DefaultsViewModel()
//        defModel.clearCallback()
        SpenderViewModel.addLocalSpender(Spender("Alex", "alexreid2070@gmail.com", 50, 1))
        SpenderViewModel.addLocalSpender(Spender("Brent", "alexreid2071@gmail.com", 50, 1))
        SpenderViewModel.addLocalSpender(Spender("Joint", "", 100, 1))
        CategoryViewModel.updateCategory(0, "Housing", "Mortgage", cDiscTypeNondiscretionary, 2, true,true)
        CategoryViewModel.updateCategory(0, "Housing", "Property Taxes", cDiscTypeNondiscretionary, 2, true, true)
        CategoryViewModel.updateCategory(0, "Housing", "Renos", cDiscTypeNondiscretionary, 2, true, true)
        CategoryViewModel.updateCategory(0, "Life", "Booze", cDiscTypeDiscretionary, 2, true, true)
        CategoryViewModel.updateCategory(0, "Life", "Annual", cDiscTypeDiscretionary, 2, true, true)
        BudgetViewModel.updateBudget("A", 1002, MyDate("2022-01-01"), 2, 100.0, cPeriodMonth, 1, cBUDGET_RECURRING, true)
        BudgetViewModel.updateBudget("B", 1003, MyDate("2022-01-01"), 2, 210.0, cPeriodMonth, 1, cBUDGET_JUST_THIS_MONTH, true)
        BudgetViewModel.updateBudget("C", 1004, MyDate("2022-01-01"), 0, 5.0, cPeriodMonth, 1, cBUDGET_RECURRING, true)
        BudgetViewModel.updateBudget("D", 1005, MyDate("2022-01-01"), 0, 10.0, cPeriodMonth, 1, cBUDGET_RECURRING, true)
        BudgetViewModel.updateBudget("E", 1005, MyDate(2022), 1, 10.0, cPeriodYear, 1, cBUDGET_RECURRING, true)
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2022-01-15"), 1.0, 1005, "test", "", 1, 1, 0, cTRANSACTION_TYPE_EXPENSE, false, 0.0, -1, 0.0, -1,"", "A"), false)
        TransactionViewModel.adjustActualsSummary(MyDate("2022-01-15"), 1005, 1, 1.0)
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2022-01-15"), 2.0, 1005, "test", "", 0, 0, 100, cTRANSACTION_TYPE_EXPENSE, false, 0.0, -1, 0.0, -1,"", "B"), false)
        TransactionViewModel.adjustActualsSummary(MyDate("2022-01-15"), 1005, 0, 2.0)
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2022-02-15"), 100.0, 1003, "test", "", 2, 2, 50, cTRANSACTION_TYPE_EXPENSE, false, 0.0, -1, 0.0, -1, "", "C"), false)
        TransactionViewModel.adjustActualsSummary(MyDate("2022-02-15"), 1003, 0, 50.0)
        TransactionViewModel.adjustActualsSummary(MyDate("2022-02-15"), 1003, 1, 50.0)
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2022-02-15"), 4.0, 1004, "test", "", 0, 0, 100, cTRANSACTION_TYPE_EXPENSE, false, 0.0, -1, 0.0, -1, "", "D"), false)
        TransactionViewModel.adjustActualsSummary(MyDate("2022-02-15"), 1004, 0, 4.0)
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2022-02-15"), 4.0, 1005, "test", "", 0, 0, 100, cTRANSACTION_TYPE_EXPENSE, false, 0.0, -1, 0.0, -1, "", "E"), false)
        TransactionViewModel.adjustActualsSummary(MyDate("2022-02-15"), 1005, 0, 4.0)
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2022-03-15"), 100.0, 1003, "test", "", 2, 2, 20, cTRANSACTION_TYPE_EXPENSE, false, 0.0, -1, 0.0, -1, "", "F"), false)
        TransactionViewModel.adjustActualsSummary(MyDate("2022-03-15"), 1003, 0, 20.0)
        TransactionViewModel.adjustActualsSummary(MyDate("2022-03-15"), 1003, 1, 80.0)
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2022-03-15"), 7.0, 1005, "test", "", 0, 0, 100, cTRANSACTION_TYPE_EXPENSE, false, 0.0, -1, 0.0, -1, "", "G"), false)
        TransactionViewModel.adjustActualsSummary(MyDate("2022-03-15"), 1005, 0, 7.0)
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2022-04-15"), 4.0, 1005, "test", "", 0, 0, 100, cTRANSACTION_TYPE_EXPENSE, false, 0.0, -1, 0.0, -1, "", "H"), false)
        TransactionViewModel.adjustActualsSummary(MyDate("2022-04-15"), 1005, 0, 4.0)

/*        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2022-01-15"), 100.0, -99, "transfer", "", 1, 2, cTRANSACTION_TYPE_EXPENSE, 0, "TransferA"), false)
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2022-01-15"), 100.0, -99, "transfer", "", 2, 1, cTRANSACTION_TYPE_EXPENSE, 100, "TransferB"), false)
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2022-02-15"), 100.0, -99, "transfer", "", 1, 2, cTRANSACTION_TYPE_EXPENSE, 0, "TransferC"), false)
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2022-02-15"), 100.0, -99, "transfer", "", 2, 1, cTRANSACTION_TYPE_EXPENSE, 100, "TransferD"), false)
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2022-03-15"), 100.0, -99, "transfer", "", 1, 2, cTRANSACTION_TYPE_EXPENSE, 0, "TransferE"), false)
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2022-03-15"), 100.0, -99, "transfer", "", 2, 1, cTRANSACTION_TYPE_EXPENSE, 100, "TransferF"), false)
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2022-04-15"), 100.0, -99, "transfer", "", 1, 2, cTRANSACTION_TYPE_EXPENSE, 0, "TransferG"), false)
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2022-04-15"), 100.0, -99, "transfer", "", 2, 1, cTRANSACTION_TYPE_EXPENSE, 100, "TransferH"), false)
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2022-05-15"), 100.0, -99, "transfer", "", 1, 2, cTRANSACTION_TYPE_EXPENSE, 0, "TransferI"), false)
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2022-05-15"), 100.0, -99, "transfer", "", 2, 1, cTRANSACTION_TYPE_EXPENSE, 100, "TransferJ"), false)
*/
        var ac = TransactionViewModel.getActualsForPeriod(1004, MyDate(2022,1,1), MyDate(2022,1,31), 0)
        Assert.assertEquals(0.0, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1004, MyDate(2022,1,1), MyDate(2022,1,1), 0)
        Assert.assertEquals(0.0, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1004, MyDate(2022,1,1), MyDate(2022,1,1), 1)
        Assert.assertEquals(0.0, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1004, MyDate(2022,1,1), MyDate(2022,1,1), 2)
        Assert.assertEquals(0.0, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1004, MyDate(2022,1,1), MyDate(2022,2,1), 1)
        Assert.assertEquals(0.0, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1004, MyDate(2022,1,1), MyDate(2022,1,31), 2)
        Assert.assertEquals(0.0, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1005, MyDate(2022,1,1), MyDate(2022,1,31), 0)
        Assert.assertEquals(2.0, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1005, MyDate(2022,1,1), MyDate(2022,1,1), 1)
        Assert.assertEquals(1.0, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1005, MyDate(2022,1,1), MyDate(2022,1,1), 2)
        Assert.assertEquals(3.0, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1005, MyDate(2022,2, 1), MyDate(2022,2,1), 0)
        Assert.assertEquals(4.0, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1005, MyDate(2022,2, 1), MyDate(2022,2,1), 1)
        Assert.assertEquals(0.0, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1005, MyDate(2022,2, 1), MyDate(2022,2,1), 2)
        Assert.assertEquals(4.0, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1005, MyDate(2022,3, 1), MyDate(2022,3,1), 0)
        Assert.assertEquals(7.0, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1005, MyDate(2022,3,1), MyDate(2022,3,1), 1)
        Assert.assertEquals(0.0, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1005, MyDate(2022,3,1), MyDate(2022,3,1), 2)
        Assert.assertEquals(7.0, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1005, MyDate(2022,4,1), MyDate(2022,4,1), 0)
        Assert.assertEquals(4.0, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1005, MyDate(2022,4,1), MyDate(2022,4,1), 1)
        Assert.assertEquals(0.0, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1005, MyDate(2022,4,1), MyDate(2022,4,1), 2)
        Assert.assertEquals(4.0, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1005, MyDate(2022,2,1), MyDate(2022,3,1), 0)
        Assert.assertEquals(11.0, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1005, MyDate(2022,2,1), MyDate(2022,3,1), 1)
        Assert.assertEquals(0.0, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1005, MyDate(2019,2,1), MyDate(3333,3,1), 0)
        Assert.assertEquals(17.0, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1005, MyDate(2019,2,1), MyDate(3333,3,1), 1)
        Assert.assertEquals(1.0, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1005, MyDate(2019,2,1), MyDate(3333,3,1), 2)
        Assert.assertEquals(18.0, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1003, MyDate(2022,1,1), MyDate(2022,1,1), 0)
        Assert.assertEquals(0.0, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1003, MyDate(2022,1,1), MyDate(2022,2,1), 0)
        Assert.assertEquals(50.0, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1003, MyDate(2022,1,1), MyDate(2022,3,1), 0)
        Assert.assertEquals(70.0, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1003, MyDate(2022,1,1), MyDate(2022,1,1), 1)
        Assert.assertEquals(0.0, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1003, MyDate(2022,1,1), MyDate(2022,2,1), 1)
        Assert.assertEquals(50.0, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1003, MyDate(2022,1,1), MyDate(2022,3,1), 1)
        Assert.assertEquals(130.0, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1003, MyDate(2022,1,1), MyDate(2022,3,1), 2)
        Assert.assertEquals(200.0, ac, 0.0)

        var bm = BudgetViewModel.getOriginalBudgetAmount(1005, MyDate("2020-01-01"), 0)
        Assert.assertEquals(0.0, bm.amount, 0.0)
        var bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate(2020,1,1), 1005, 0)
        Assert.assertEquals(0.0, bmr, 0.0)

        bm = BudgetViewModel.getOriginalBudgetAmount(1005, MyDate("2022-01-01"), 0)
        Assert.assertEquals(10.0, bm.amount, 0.0)
        Assert.assertEquals(1, bm.startDate.getMonth())
        Assert.assertEquals(1, bm.applicableDate.getMonth())
        ac = TransactionViewModel.getActualsForPeriod(1005, MyDate(2022,1,1), MyDate(2022,1,1), 0)
        Assert.assertEquals(2.0, ac, 0.0)
        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate(2022,1,1), 1005, 0)
        Assert.assertEquals(10.0, bmr, 0.0)

        bm = BudgetViewModel.getOriginalBudgetAmount(1005, MyDate("2022-02-01"), 0)
        Assert.assertEquals(10.0, bm.amount, 0.0)
        Assert.assertEquals(1, bm.startDate.getMonth())
        Assert.assertEquals(1, bm.applicableDate.getMonth())
        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate(2022,2,1), 1005, 0)
        Assert.assertEquals(10.0, bmr, 0.0)

        bm = BudgetViewModel.getOriginalBudgetAmount(1005, MyDate("2022-03-01"), 0)
        Assert.assertEquals(10.0, bm.amount, 0.0)
        Assert.assertEquals(1, bm.startDate.getMonth())
        Assert.assertEquals(1, bm.applicableDate.getMonth())
        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate(2022,3,1), 1005, 0)
        Assert.assertEquals(10.0, bmr, 0.0)

        bm = BudgetViewModel.getOriginalBudgetAmount(1005, MyDate("2022-04-01"), 0)
        Assert.assertEquals(10.0, bm.amount, 0.0)
        Assert.assertEquals(1, bm.startDate.getMonth())
        Assert.assertEquals(1, bm.applicableDate.getMonth())
        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate(2022,4,1), 1005, 0)
        Assert.assertEquals(10.0, bmr, 0.0)

        bm = BudgetViewModel.getOriginalBudgetAmount(1005, MyDate("2022-01-01"), 1)
        Assert.assertEquals(10.0, bm.amount, 0.0)
        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate("2022-01-01"), 1005, 1)
        Assert.assertEquals(1.0, bmr, 0.0)
        bm = BudgetViewModel.getOriginalBudgetAmount(1005, MyDate("2022-01-01"), 2)
        Assert.assertEquals(0.0, bm.amount, 0.0)
        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate("2022-01-01"), 1005, 2)
        Assert.assertEquals(11.0, bmr, 0.0)

        bm = BudgetViewModel.getOriginalBudgetAmount(1004, MyDate("2022-01-01"), 0)
        Assert.assertEquals(5.0, bm.amount, 0.0)
        var bm2 = BudgetViewModel.budgetExistsForExactPeriod(1004, MyDate("2022-01-01"), 0)
        Assert.assertEquals(5.0, bm2, 0.0)

        bm = BudgetViewModel.getOriginalBudgetAmount(1004, MyDate("2022-01-01"), 2)
        Assert.assertEquals(0.0, bm.amount, 0.0)
        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate("2022-01-01"), 1004, 2)
        Assert.assertEquals(5.0, bmr, 0.0)

        bm = BudgetViewModel.getOriginalBudgetAmount(1004, MyDate("2022-01-01"), 1)
        Assert.assertEquals(0.0, bm.amount, 0.0)
        bm2 = BudgetViewModel.budgetExistsForExactPeriod(1004, MyDate("2022-01-01"), 1)
        Assert.assertEquals(0.0, bm2, 0.0)
        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate("2022-01-01"), 1004, 1)
        Assert.assertEquals(0.0, bmr, 0.0)

        bm2 = BudgetViewModel.budgetExistsForExactPeriod(1004, MyDate("2022-01-01"), 0)
        Assert.assertEquals(5.0, bm2, 0.0)

        var catBudgets = BudgetViewModel.getCategoryBudgets(DateRangeEnum.MONTH, MyDate(2022,1,1), cDiscTypeDiscretionary, 0, "")
        var totalBudget = 0.0
        for (budget in catBudgets) {
            totalBudget += budget.value.toFloat()
        }
        var totAc = TransactionViewModel.getTotalActualsForRange(MyDate("2022-01-01"), MyDate("2022-01-31"),
            cDiscTypeDiscretionary, 0)
        Assert.assertEquals(2.0, totAc, 0.0)
        Assert.assertEquals(15.0, totalBudget, 0.0)

        catBudgets = BudgetViewModel.getCategoryBudgets(DateRangeEnum.MONTH, MyDate(2022,1,1), cDiscTypeDiscretionary, 1, "")
        totalBudget = 0.0
        for (budget in catBudgets) {
            totalBudget += budget.value.toFloat()
        }
        totAc = TransactionViewModel.getTotalActualsForRange(MyDate("2022-01-01"), MyDate("2022-01-31"),
            cDiscTypeDiscretionary, 1)
        Assert.assertEquals(1.0, totAc, 0.0)
        Assert.assertEquals(1.0, totalBudget, 0.0)

        catBudgets = BudgetViewModel.getCategoryBudgets(DateRangeEnum.MONTH, MyDate(2022,1,1), cDiscTypeDiscretionary, 2, "")
        totalBudget = 0.0
        for (budget in catBudgets) {
            totalBudget += budget.value.toFloat()
        }
        totAc = TransactionViewModel.getTotalActualsForRange(MyDate("2022-01-01"), MyDate("2022-01-31"),
            cDiscTypeDiscretionary, 2)
        Assert.assertEquals(3.0, totAc, 0.0)
        Assert.assertEquals(16.0, totalBudget, 0.0)

        catBudgets = BudgetViewModel.getCategoryBudgets(DateRangeEnum.MONTH, MyDate(2022,1,1), cDiscTypeNondiscretionary, 0, "")
        totalBudget = 0.0
        for (budget in catBudgets) {
            totalBudget += budget.value.toFloat()
        }
        totAc = TransactionViewModel.getTotalActualsForRange(MyDate("2022-01-01"), MyDate("2022-01-31"),
            cDiscTypeNondiscretionary, 0)
        Assert.assertEquals(0.0, totAc, 0.0)
        Assert.assertEquals(155.0, totalBudget, 0.0)

        catBudgets = BudgetViewModel.getCategoryBudgets(DateRangeEnum.MONTH, MyDate(2022,1,1), cDiscTypeNondiscretionary, 1, "")
        totalBudget = 0.0
        for (budget in catBudgets) {
            totalBudget += budget.value.toFloat()
        }
        totAc = TransactionViewModel.getTotalActualsForRange(MyDate("2022-01-01"), MyDate("2022-01-31"),
            cDiscTypeNondiscretionary, 1)
        Assert.assertEquals(0.0, totAc, 0.0)
        Assert.assertEquals(155.0, totalBudget, 0.0)

        catBudgets = BudgetViewModel.getCategoryBudgets(DateRangeEnum.MONTH, MyDate(2022,1,1), cDiscTypeNondiscretionary, 2, "")
        totalBudget = 0.0
        for (budget in catBudgets) {
            totalBudget += budget.value.toFloat()
        }
        totAc = TransactionViewModel.getTotalActualsForRange(MyDate("2022-01-01"), MyDate("2022-01-31"),
            cDiscTypeNondiscretionary, 2)
        Assert.assertEquals(0.0, totAc, 0.0)
        Assert.assertEquals(310.0, totalBudget, 0.0)

        catBudgets = BudgetViewModel.getCategoryBudgets(DateRangeEnum.MONTH, MyDate(2022,1,1), cDiscTypeAll, 0, "")
        totalBudget = 0.0
        for (budget in catBudgets) {
            totalBudget += budget.value.toFloat()
        }
        totAc = TransactionViewModel.getTotalActualsForRange(MyDate("2022-01-01"), MyDate("2022-01-31"),
            cDiscTypeAll, 0)
        Assert.assertEquals(2.0, totAc, 0.0)
        Assert.assertEquals(170.0, totalBudget, 0.0)

        catBudgets = BudgetViewModel.getCategoryBudgets(DateRangeEnum.MONTH, MyDate(2022,1,1), cDiscTypeAll, 1, "")
        totalBudget = 0.0
        for (budget in catBudgets) {
            totalBudget += budget.value.toFloat()
        }
        totAc = TransactionViewModel.getTotalActualsForRange(MyDate("2022-01-01"), MyDate("2022-01-31"),
            cDiscTypeAll, 1)
        Assert.assertEquals(1.0, totAc, 0.0)
        Assert.assertEquals(156.0, totalBudget, 0.0)

        catBudgets = BudgetViewModel.getCategoryBudgets(DateRangeEnum.MONTH, MyDate(2022,1,1), cDiscTypeAll, 2, "")
        totalBudget = 0.0
        for (budget in catBudgets) {
            totalBudget += budget.value.toFloat()
        }
        totAc = TransactionViewModel.getTotalActualsForRange(MyDate("2022-01-01"), MyDate("2022-01-31"),
            cDiscTypeAll, 2)
        Assert.assertEquals(3.0, totAc, 0.0)
        Assert.assertEquals(326.0, totalBudget, 0.0)

        catBudgets = BudgetViewModel.getCategoryBudgets(DateRangeEnum.MONTH, MyDate(2022,2,1), cDiscTypeDiscretionary, 0, "")
        totalBudget = 0.0
        for (budget in catBudgets) {
            totalBudget += budget.value.toFloat()
        }
        totAc = TransactionViewModel.getTotalActualsForRange(MyDate("2022-02-01"), MyDate("2022-02-28"),
            cDiscTypeDiscretionary, 0)
        Assert.assertEquals(8.0, totAc, 0.0)
        Assert.assertEquals(15.0, totalBudget, 0.0)

        bm = BudgetViewModel.getOriginalBudgetAmount(1002, MyDate("2022-01-01"), 0)
        Assert.assertEquals(0.0, bm.amount, 0.0)
        bm2 = BudgetViewModel.budgetExistsForExactPeriod(1002, MyDate("2022-01-01"), 0)
        Assert.assertEquals(0.0, bm2, 0.0)
        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate("2022-01-01"), 1002, 0)
        Assert.assertEquals(50.0, bmr, 0.0)
        bm = BudgetViewModel.getOriginalBudgetAmount(1002, MyDate("2022-01-01"), 1)
        Assert.assertEquals(0.0, bm.amount, 0.0)
        bm2 = BudgetViewModel.budgetExistsForExactPeriod(1002, MyDate("2022-01-01"), 1)
        Assert.assertEquals(0.0, bm2, 0.0)
        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate("2022-01-01"), 1002, 1)
        Assert.assertEquals(50.0, bmr, 0.0)
        bm = BudgetViewModel.getOriginalBudgetAmount(1002, MyDate("2022-01-01"), 2)
        Assert.assertEquals(100.0, bm.amount, 0.0)
        bm2 = BudgetViewModel.budgetExistsForExactPeriod(1002, MyDate("2022-01-01"), 2)
        Assert.assertEquals(100.0, bm2, 0.0)
        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate("2022-01-01"), 1002, 2)
        Assert.assertEquals(100.0, bmr, 0.0)

        bm = BudgetViewModel.getOriginalBudgetAmount(1002, MyDate("2022-02-01"), 0)
        Assert.assertEquals(0.0, bm.amount, 0.0)
        bm2 = BudgetViewModel.budgetExistsForExactPeriod(1002, MyDate("2022-02-01"), 0)
        Assert.assertEquals(0.0, bm2, 0.0)
        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate("2022-02-01"), 1002, 0)
        Assert.assertEquals(50.0, bmr, 0.0)
        bm = BudgetViewModel.getOriginalBudgetAmount(1002, MyDate("2022-02-01"), 1)
        Assert.assertEquals(0.0, bm.amount, 0.0)
        bm2 = BudgetViewModel.budgetExistsForExactPeriod(1002, MyDate("2022-02-01"), 1)
        Assert.assertEquals(0.0, bm2, 0.0)
        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate("2022-02-01"), 1002, 1)
        Assert.assertEquals(50.0, bmr, 0.0)
        bm = BudgetViewModel.getOriginalBudgetAmount(1002, MyDate("2022-02-01"), 2)
        Assert.assertEquals(100.0, bm.amount, 0.0)
        bm2 = BudgetViewModel.budgetExistsForExactPeriod(1002, MyDate("2022-02-01"), 2)
        Assert.assertEquals(0.0, bm2, 0.0)
        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate("2022-02-01"), 1002, 2)
        Assert.assertEquals(100.0, bmr, 0.0)

        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate("2022-02-01"), 1003, 0)
        Assert.assertEquals(0.0, bmr, 0.0)

        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate("2022-03-01"), 1003, 0)
        Assert.assertEquals(0.0, bmr, 0.0)
        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate("2022-03-01"), 1003, 1)
        Assert.assertEquals(0.0, bmr, 0.0)
        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate("2022-03-01"), 1003, 2)
        Assert.assertEquals(0.0, bmr, 0.0)

        CategoryViewModel.updateCategory(0, "Life", "JointBudgetIndependentActuals", cDiscTypeDiscretionary, 2, true, true)
        BudgetViewModel.updateBudget("F", 1006, MyDate("2022-01-01"),2, 100.0, cPeriodMonth, 1, cBUDGET_RECURRING, true)
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2022-01-15"), 5.0, 1006, "test", "", 0, 0, 100, cTRANSACTION_TYPE_EXPENSE, false, 0.0, -1, 0.0, -1, "", "AA"), false)
        TransactionViewModel.adjustActualsSummary(MyDate("2022-01-15"), 1006, 0, 5.0)
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2022-01-15"), 6.0, 1006, "test", "", 1, 1, 0, cTRANSACTION_TYPE_EXPENSE, false, 0.0, -1, 0.0, -1, "", "AB"), false)
        TransactionViewModel.adjustActualsSummary(MyDate("2022-01-15"), 1006, 1, 6.0)
        ac = TransactionViewModel.getActualsForPeriod(1006, MyDate(2022,1,1), MyDate(2022,1,1), 0)
        Assert.assertEquals(5.0, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1006, MyDate(2022,1,1), MyDate(2022,1,1), 1)
        Assert.assertEquals(6.0, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1006, MyDate(2022,1,1), MyDate(2022,1,1), 2)
        Assert.assertEquals(11.0, ac, 0.0)
        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate("2022-01-01"), 1006, 0)
        Assert.assertEquals(50.0, bmr, 0.0)
        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate("2022-01-01"), 1006, 1)
        Assert.assertEquals(50.0, bmr, 0.0)
        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate("2022-01-01"), 1006, 2)
        Assert.assertEquals(100.0, bmr, 0.0)
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2022-02-15"), 100.0,1006, "test", "", 0, 0, 100, cTRANSACTION_TYPE_EXPENSE, false, 0.0, -1, 0.0, -1, "", "AC"), false)
        TransactionViewModel.adjustActualsSummary(MyDate("2022-02-15"), 1006, 0, 100.0)
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2022-02-15"), 50.0, 1006, "test", "", 1, 1, 0, cTRANSACTION_TYPE_EXPENSE, false, 0.0, -1, 0.0, -1, "", "AD"), false)
        TransactionViewModel.adjustActualsSummary(MyDate("2022-02-15"), 1006, 1, 50.0)
        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate("2022-02-01"), 1006, 0)
        Assert.assertEquals(50.0, bmr, 0.0)
        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate("2022-02-01"), 1006, 1)
        Assert.assertEquals(50.0, bmr, 0.0)
        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate("2022-02-01"), 1006, 2)
        Assert.assertEquals(100.0, bmr, 0.0)

//        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2022-01-15"), 1.0, 1005, "test", "", 1, 1, cTRANSACTION_TYPE_EXPENSE, 0, "D"), false)
//        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2022-01-15"), 2.0, 1005, "test", "", 0, 0, cTRANSACTION_TYPE_EXPENSE, 100, "E"), false)
//        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2022-02-15"), 4.0, 1005, "test", "", 0, 0, cTRANSACTION_TYPE_EXPENSE, 100, "F"), false)
//        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2022-03-15"), 7.0, 1005, "test", "", 0, 0, cTRANSACTION_TYPE_EXPENSE, 100, "G"), false)
//        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2022-04-15"), 4.0, 1005, "test", "", 0, 0, cTRANSACTION_TYPE_EXPENSE, 100, "H"), false)
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2022-03-15"), 25.0, 1005, "test", "", 2, 2, 50, cTRANSACTION_TYPE_EXPENSE, false, 0.0, -1, 0.0, -1, "", "AE"), false)
        TransactionViewModel.adjustActualsSummary(MyDate("2022-03-15"), 1005, 0, 12.50)
        TransactionViewModel.adjustActualsSummary(MyDate("2022-03-15"), 1005, 1, 12.50)
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2022-04-15"), 140.0, 1005, "test", "", 2, 2, 50, cTRANSACTION_TYPE_EXPENSE, false, 0.0, -1, 0.0, -1, "", "AF"), false)
        TransactionViewModel.adjustActualsSummary(MyDate("2022-04-15"), 1005, 0, 70.0)
        TransactionViewModel.adjustActualsSummary(MyDate("2022-04-15"), 1005, 1, 70.0)

        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate("2022-03-01"), 1005, 0)
        Assert.assertEquals(10.0, bmr, 0.0)
        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate("2022-03-01"), 1005, 1)
        Assert.assertEquals(9.0, bmr, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1005, MyDate(2022,3,1), MyDate(2022,3,1), 0)
        Assert.assertEquals(19.5, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1005, MyDate(2022,3,1), MyDate(2022,3,1), 1)
        Assert.assertEquals(12.5, ac, 0.0)
        ac = TransactionViewModel.getActualsForPeriod(1005, MyDate(2022,3,1), MyDate(2022,3,1), 2)
        Assert.assertEquals(32.0, ac, 0.0)
        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate("2022-03-01"), 1005, 2)
        Assert.assertEquals(19.0, bmr, 0.0)
        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate("2022-04-01"), 1005, 0)
        Assert.assertEquals(10.0, bmr, 0.0)
        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate("2022-04-01"), 1005, 1)
        Assert.assertEquals(0.0, bmr, 0.0)
        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate("2022-04-01"), 1005, 2)
        Assert.assertEquals(10.0, bmr, 0.0)

        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate("2022-05-01"), 1002, 2)
        Assert.assertEquals(100.0, bmr, 0.0)
        BudgetViewModel.updateBudget("A2", 1002, MyDate("2022-05-06"), 2, 20.0, cPeriodWeek, 2, cBUDGET_RECURRING, true)
        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate("2022-05-01"), 1002, 2)
        Assert.assertEquals(140.0, bmr, 0.0)
        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate("2022-06-01"), 1002, 2)
        Assert.assertEquals(40.0, bmr, 0.0)
        bmr = BudgetViewModel.getCalculatedBudgetAmount(MyDate("2022-07-01"), 1002, 2)
        Assert.assertEquals(60.0, bmr, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 20.0, 1005, "test", "", 0, 0, 100, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 0, 0.0, -1, "", "BA"), false)
        TransactionViewModel.adjustActualsSummary(MyDate("2023-01-15"), 1005, 0, 20.0)
        ac = TransactionViewModel.getActualsForPeriod(1005, MyDate(2023,1,1), MyDate(2023,1,1), 0)
        Assert.assertEquals(20.0, ac, 0.0)
        var toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(0.0, toriginal, 0.0)
        var tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(0.0, tinsurance, 0.0)
        var ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(0.0, ttotal, 0.0)

        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 40.0, 1005, "test", "", 0, 1, 0, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 0, 0.0, -1, "", "BB"), false)
        TransactionViewModel.adjustActualsSummary(MyDate("2023-01-15"), 1005, 1, 40.0)
        ac = TransactionViewModel.getActualsForPeriod(1005, MyDate(2023,1,1), MyDate(2023,1,1), 1)
        Assert.assertEquals(40.0, ac, 0.0)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(-40.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(10.0, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(-30.0, ttotal, 0.0)

        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 140.0, 1005, "test", "", 1, 0, 100, cTRANSACTION_TYPE_EXPENSE, true, 25.0, 0, 35.0, 1, "", "BC"), false)
        TransactionViewModel.adjustActualsSummary(MyDate("2023-01-15"), 1005, 0, 140.0)
        ac = TransactionViewModel.getActualsForPeriod(1005, MyDate(2023,1,1), MyDate(2023,1,1), 0)
        Assert.assertEquals(160.0, ac, 0.0)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(100.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(-25.0, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(75.0, ttotal, 0.0)

        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 102.0, 1005, "test", "", 0, 1, 0, cTRANSACTION_TYPE_EXPENSE, true, 38.0, 0, 39.0, 1, "", "BD"), false)
        TransactionViewModel.adjustActualsSummary(MyDate("2023-01-15"), 1005, 1, 102.0)
        ac = TransactionViewModel.getActualsForPeriod(1005, MyDate(2023,1,1), MyDate(2023,1,1), 1)
        Assert.assertEquals(142.0, ac, 0.0)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(-2.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(13.0, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(11.0, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 100.0, 1005, "test", "", 2, 0, 100, cTRANSACTION_TYPE_EXPENSE, true, 38.0, 0, 39.0, 1, "", "BE"), false)
        TransactionViewModel.adjustActualsSummary(MyDate("2023-01-15"), 1005, 0, 100.0)
        ac = TransactionViewModel.getActualsForPeriod(1005, MyDate(2023,1,1), MyDate(2023,1,1), 0)
        Assert.assertEquals(100.0, ac, 0.0)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(50.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(-39.0, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(11.0, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 100.0, 1005, "test", "", 2, 1, 0, cTRANSACTION_TYPE_EXPENSE, true, 38.0, 0, 39.0, 1, "", "BF"), false)
        TransactionViewModel.adjustActualsSummary(MyDate("2023-01-15"), 1005, 1, 100.0)
        ac = TransactionViewModel.getActualsForPeriod(1005, MyDate(2023,1,1), MyDate(2023,1,1), 1)
        Assert.assertEquals(100.0, ac, 0.0)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(-50.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(38.0, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(-12.0, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 100.0, 1005, "test", "", 2, 2, 40, cTRANSACTION_TYPE_EXPENSE, true, 38.0, 0, 39.0, 1, "", "BG"), false)
        TransactionViewModel.adjustActualsSummary(MyDate("2023-01-15"), 1005, 0, 40.0)
        TransactionViewModel.adjustActualsSummary(MyDate("2023-01-15"), 1005, 1, 60.0)
        ac = TransactionViewModel.getActualsForPeriod(1005, MyDate(2023,1,1), MyDate(2023,1,1), 1)
        Assert.assertEquals(60.0, ac, 0.0)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(-10.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(-.5, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(-10.5, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 0, 0, 100, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 0, 18.0, 1, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(0.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(-18.0, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(-18.0, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 0, 1, 0, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 0, 18.0, 1, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(-50.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(10.0, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(-40.0, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 0, 2, 40, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 0, 18.0, 1, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(-30.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(-4.0, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(-34.0, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 1, 0, 100, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 0, 18.0, 1, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(50.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(-18.0, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(32.0, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 1, 1, 0, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 0, 18.0, 1, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(0.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(10.0, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(10.0, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 1, 2, 40, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 0, 18.0, 1, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(20.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(-4.0, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(16.0, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 2, 0, 100, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 0, 18.0, 1, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(25.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(-18.0, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(7.0, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 2, 1, 0, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 0, 18.0, 1, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(-25.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(10.0, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(-15.0, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 2, 2, 40, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 0, 18.0, 1, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(-5.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(-4.0, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(-9.0, ttotal, 0.0)

        SpenderViewModel.updateSpenderSplits(30, true)
        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 0, 0, 100, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 0, 18.0, 1, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(0.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(-18.0, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(-18.0, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 0, 1, 0, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 0, 18.0, 1, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(-50.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(10.0, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(-40.0, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 0, 2, 40, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 0, 18.0, 1, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(-30.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(1.6, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(-28.4, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 1, 0, 100, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 0, 18.0, 1, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(50.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(-18.0, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(32.0, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 1, 1, 0, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 0, 18.0, 1, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(0.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(10.0, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(10.0, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 1, 2, 40, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 0, 18.0, 1, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(20.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(1.6, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(21.6, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 2, 0, 100, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 0, 18.0, 1, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(35.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(-18.0, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(17.0, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 2, 1, 0, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 0, 18.0, 1, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(-15.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(10.0, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(-5.0, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 2, 2, 40, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 0, 18.0, 1, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(5.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(1.6, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(6.6, ttotal, 0.0)

        SpenderViewModel.updateSpenderSplits(40, true)
        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 0, 0, 100, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 2, 18.0, 2, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(0.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(-16.80, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(-16.80, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 0, 1, 0, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 2, 18.0, 2, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(-50.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(11.20, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(-38.80, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 0, 2, 40, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 2, 18.0, 2, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(-30.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(0.0, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(-30.0, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 1, 0, 100, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 2, 18.0, 2, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(50.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(-16.8, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(33.2, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 1, 1, 0, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 2, 18.0, 2, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(0.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(11.2, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(11.2, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 1, 2, 40, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 2, 18.0, 2, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(20.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(0.0, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(20.0, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 2, 0, 100, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 2, 18.0, 2, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(30.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(-16.8, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(13.2, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 2, 1, 0, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 2, 18.0, 2, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(-20.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(11.2, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(-8.8, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 2, 2, 40, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 2, 18.0, 2, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(0.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(0.0, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(0.0, ttotal, 0.0)

        SpenderViewModel.updateSpenderSplits(50, true)
        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 0, 0, 100, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 2, 18.0, 2, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(0.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(-14.0, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(-14.0, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 0, 1, 0, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 2, 18.0, 2, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(-50.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(14.0, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(-36.0, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 0, 2, 40, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 2, 18.0, 2, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(-30.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(2.8, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(-27.2, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 1, 0, 100, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 2, 18.0, 2, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(50.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(-14.0, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(36.0, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 1, 1, 0, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 2, 18.0, 2, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(0.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(14.0, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(14.0, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 1, 2, 40, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 2, 18.0, 2, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(20.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(2.8, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(22.8, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 2, 0, 100, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 2, 18.0, 2, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(25.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(-14.0, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(11.0, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 2, 1, 0, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 2, 18.0, 2, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(-25.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(14.0, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(-11.0, ttotal, 0.0)

        TransactionViewModel.resetTransactionList()
        TransactionViewModel.addTransactionLocal(Transaction(MyDate("2023-01-15"), 50.0, 1005, "test", "", 2, 2, 40, cTRANSACTION_TYPE_EXPENSE, true, 10.0, 2, 18.0, 2, "", "BH"), false)
        toriginal = TransactionViewModel.getTotalAOwesBOriginalAmount()
        Assert.assertEquals(-5.0, toriginal, 0.0)
        tinsurance = TransactionViewModel.getTotalAOwesBInsuranceAmount()
        Assert.assertEquals(2.8, tinsurance, 0.0)
        ttotal = TransactionViewModel.getTotalAOwesB()
        Assert.assertEquals(-2.2, ttotal, 0.0)

    }
}